name: Rust

on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Make .env file because macros cant be created without the presence of the .env file
        run: |
          cd ${{  github.workspace }}
          cp .env.example .env

      - name: Build project
        run: cargo build --verbose
