name: Rust

on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        run: |
          ls ${{  github.workspace }}
          cd ${{  github.workspace }}
          cp .env.example .env

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: dotenv
          path: .env

      - name: Build project
        run: cargo build --verbose
