name: Rust

on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          TRIGGER_APP: Chrome.exe
          RUN_APP: 'C:\\Program Files\\Spotify\\Spotify.exe'

      - name: Build project
        run: cargo build --verbose
